
export type Publication = {
  id: number;
  title: string;
  authors: string;
  year: number;
  institution: string;
  tags: string[];
  conclusion: string;
  nextSteps: string;
};

export const publications: Publication[] = [
    { id: 1, title: 'Microgravity effects on Arabidopsis thaliana root development', authors: 'A. Jensen, B. Carlsson', year: 2022, institution: 'JPL', tags: ['Plant Science', 'Genetics'], conclusion: 'Root skewing is significantly altered in microgravity, suggesting gravisensing pathways are disrupted.', nextSteps: 'Investigate specific gene expression changes in root tip meristems.' },
    { id: 2, title: 'Long-term Spaceflight and its Impact on Human Bone Density', authors: 'C. Evans, D. Smith', year: 2021, institution: 'Johnson Space Center', tags: ['Human Health', 'Physiology'], conclusion: 'Astronauts on missions over 6 months show an average of 11% bone density loss in weight-bearing bones.', nextSteps: 'Test new exercise countermeasures and dietary supplements.' },
    { id: 3, title: 'Psychological Resilience in Isolated, Confined Environments', authors: 'F. Williams, G. Harris', year: 2023, institution: 'Ames Research Center', tags: ['Human Health', 'Psychology'], conclusion: 'Team cohesion and regular communication with Earth are critical for maintaining psychological health.', nextSteps: 'Develop VR-based recreational activities to combat monotony.' },
    { id: 4, title: 'Fungal Growth on Spacecraft Materials', authors: 'H. Ivanov, I. Petrov', year: 2019, institution: 'Roscosmos', tags: ['Microbiology', 'Materials Science'], conclusion: 'Certain fungal species can degrade polymer-based materials, posing a risk to long-term missions.', nextSteps: 'Develop antimicrobial coatings for interior surfaces.' },
    { id: 5, title: 'Cellular Response to Cosmic Radiation', authors: 'J. Lee, K. Patel', year: 2020, institution: 'Glenn Research Center', tags: ['Genetics', 'Human Health'], conclusion: 'Increased DNA damage and repair mechanism activation observed in human cell cultures exposed to simulated GCR.', nextSteps: 'Evaluate shielding effectiveness of new composite materials.' },
    { id: 6, title: 'Nutrient Production from Algae Bioreactors in Space', authors: 'L. Martinez', year: 2022, institution: 'ESA', tags: ['Life Support', 'Plant Science'], conclusion: 'Spirulina algae can be cultivated in a closed-loop system to produce a high-protein food source.', nextSteps: 'Optimize bioreactor efficiency and taste of the final product.' },
    { id: 7, title: 'Vestibular System Adaptation to Zero-G', authors: 'M. Chen', year: 2018, institution: 'CNSA', tags: ['Human Health', 'Physiology'], conclusion: 'The otolith organs show significant adaptation within the first 72 hours of spaceflight, leading to space adaptation syndrome.', nextSteps: 'Pre-flight adaptation protocols using centrifugation.' },
    { id: 8, title: 'Comparative Genomics of Bacteria in the ISS Environment', authors: 'N. O\'Malley', year: 2023, institution: 'JAXA', tags: ['Microbiology', 'Genetics'], conclusion: 'Some bacterial strains exhibit increased antibiotic resistance after prolonged exposure to the ISS environment.', nextSteps: 'Identify the genetic markers responsible for this increased resistance.' },
    { id: 9, title: 'Cardiovascular Deconditioning During Spaceflight', authors: 'R. Garcia, S. Kim', year: 2021, institution: 'Johnson Space Center', tags: ['Human Health', 'Physiology'], conclusion: 'Orthostatic intolerance is a common post-flight issue due to fluid shifts and cardiac remodeling.', nextSteps: 'Investigate lower body negative pressure as a countermeasure.' },
    { id: 10, title: 'Microbial Dynamics on the International Space Station Surfaces', authors: 'E. Fischer, M. Weber', year: 2020, institution: 'German Aerospace Center (DLR)', tags: ['Microbiology', 'Planetary Protection'], conclusion: 'A core microbiome exists on the ISS, dominated by human-associated bacteria.', nextSteps: 'Track microbial succession over multiple crew rotations.' },
    { id: 11, title: 'Effect of Hypercapnia on Cognitive Performance', authors: 'A. Bell, T. Scott', year: 2022, institution: 'Ames Research Center', tags: ['Human Health', 'Psychology'], conclusion: 'Elevated CO2 levels, even within current ISS limits, can lead to decreased complex cognitive function.', nextSteps: 'Refine CO2 scrubbing technology for long-duration missions.' },
    { id: 12, title: 'Radiation-Induced Cataracts in Astronauts', authors: 'K. Watanabe, H. Sato', year: 2019, institution: 'JAXA', tags: ['Human Health', 'Ophthalmology'], conclusion: 'A higher incidence of posterior subcapsular cataracts is observed in astronauts, correlated with space radiation dose.', nextSteps: 'Develop radioprotective agents and improved helmet visor shielding.' },
    { id: 13, title: 'Spaceflight-Associated Neuro-ocular Syndrome (SANS)', authors: 'P. Williams, L. Brown', year: 2023, institution: 'Johnson Space Center', tags: ['Human Health', 'Ophthalmology', 'Physiology'], conclusion: 'SANS is characterized by optic disc edema and choroidal folds, likely due to cephalad fluid shifts.', nextSteps: 'Utilize Chibis suit and thigh cuffs to mitigate fluid shifts.' },
    { id: 14, title: 'Cultivation of Dwarf Wheat in Microgravity', authors: 'B. Ivanova, V. Smirnov', year: 2018, institution: 'Roscosmos', tags: ['Plant Science', 'Life Support'], conclusion: 'Dwarf wheat can complete a full life cycle in space, but with lower seed yield compared to ground controls.', nextSteps: 'Optimize lighting and nutrient delivery to improve yield.' },
    { id: 15, title: 'T-cell Activation and Immune System Dysregulation', authors: 'S. Miller, J. Davis', year: 2020, institution: 'Kennedy Space Center', tags: ['Human Health', 'Immunology'], conclusion: 'Microgravity inhibits T-cell activation, a key factor in the observed immune dysregulation in astronauts.', nextSteps: 'Screen for compounds that can restore T-cell function in vitro.' },
    { id: 16, title: 'Behavioral Health and Performance in Mars Analog Missions', authors: 'C. Johnson, M. Rodriguez', year: 2022, institution: 'HI-SEAS', tags: ['Human Health', 'Psychology'], conclusion: 'Autonomy and meaningful work are key predictors of crew morale and performance in long-duration isolation.', nextSteps: 'Integrate AI-driven scheduling tools to optimize crew tasks.' },
];
